[package]
name = "lkdiff"
version = "0.1.0"
edition = "2021"
default-run = "lkdiff"

[[bin]]
name = "trace_mmap"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.2"
once_cell = "1.19.0"